baseURL: https://popov1024.github.io
theme: soho
title: Andrey Popov
defaultContentLanguage: ru
footnoteReturnLinkContents: ↩
hasCJKLanguage: true
paginate: 7
enableEmoji: true
PygmentsCodeFences: false
summarylength: 10
permalinks:
  posts: /:filename/

params:
    profilePicture: "images/profile.png"
    copyright: "Andrey Popov"
taxonomies:
    category : categories
    tag : tags
    series : series
outputFormats:          # use for search. recommend not to modify 
  SearchIndex:
    mediaType: "application/json"
    baseName: "searchindex"
    isPlainText: true
    notAlternative: true

outputs:
    home: ["HTML", "RSS", "SearchIndex"]  # recommend not to modify
# sitemap
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

menu:
  main:
    - identifier: posts
      name: Posts
      title: Posts
      url: /posts/
      weight: 100