baseURL: https://popov1024.github.io/
theme: soho
title: Andrey Popov
defaultContentLanguage: ru
footnoteReturnLinkContents: ↩
hasCJKLanguage: true
paginate: 7
enableEmoji: true
PygmentsCodeFences: false
summarylength: 10
permalinks:
  posts: /:filename/

params:
    profilePicture: "images/profile.png"
    copyright: "Andrey Popov"
    socialIcons:
      - github:
        icon: "fa-github"
        title: "Github"
        url: "https://github.com/popov1024"
      - twitter:
        icon: "fa-twitter"
        title: "Twitter"
        url: "https://twitter.com/andrey_popov"
taxonomies:
    category : categories
    tag : tags
    series : series

outputs:
    home: ["HTML", "RSS"]

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

menu:
  main:
    - identifier: posts
      name: Posts
      title: Posts
      url: /posts/
      weight: 100
    - identifier: tags
      name: Tags
      title: Tags
      url: /tags/
      weight: 200